CREATE DATABASE XYZ_COMPANY;

USE  XYZ_COMPANY;

CREATE TABLE EMPLOYEE(
ID  INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY FLOAT
);

INSERT INTO  EMPLOYEE
(ID,Name,SALARY)
VALUES
(101,"SHIVAM",230000),
(208,"VISHAL",45000);

SELECT*FROM EMPLOYEE ;