-- WRITE THE QUERY TO FIND THE AVG MARKS IN EACH CITY IN ASCENDING & DESCENDING ORDER ?
-- EACH IS MAINLY USED FOR GROUPING CLAUSE

CREATE DATABASE UNIVERSITY_PRATICE_SET2;

USE UNIVERSITY_PRATICE_SET2;

CREATE TABLE student1(
rollno INT PRIMARY KEY ,
name VARCHAR(50) ,
marks INT NOT NULL,
grade VARCHAR(50) ,  
city VARCHAR(50)
);
 
INSERT INTO student1
 (rollno,name,marks,grade,city)
 VALUES 
(101,"SHIVAM",78,"A","NOIDA"),
(102,"VISAHL",73,"B","GHAZIABAD"),
(103,"KARAN",78,"C","DELHI"),
(104,"MANISHA",78,"A","DELHI"),
(105,"AKASH",78,"D","NOIDA"),
(106,"MAJOR",78,"C","GHAZIABAD");

SELECT city,AVG(marks) FROM student1 GROUP BY city
ORDER BY city ASC;

SELECT city,AVG(marks) FROM student1 GROUP BY city
ORDER BY city DESC;
